version: 2
jobs:
  prepare:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Build apk
          command: ./gradlew assembleRelease
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports
      - run:
          name: Copy apk
          command: |
            mkdir -p dist
            cp -r app/build/outputs/apk/release/*.apk dist/${CIRCLE_PROJECT_REPONAME}-release.apk
      - store_artifacts:
          path: dist
          destination: dist
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples

      # https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job.
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: ./
          # Must be relative path from root
          paths:
            - dist

  #Upload when git have tag
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: persisted
      - run:
          name: List Files
          command: |
            apk add tree
            pwd
            tree persisted
      - run:
          name: Publish Release on GitHub
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} persisted/dist

  #Upload to bintray
  publish-to-maven:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Publish to Jcenter and Maven Central
          command: ./gradlew build bintrayUpload -PdryRun=false
      - run:
          name: Publish to Github Package
          command: ./gradlew publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - prepare
      - publish-github-release:
          requires:
            - prepare
          filters:
            branches:
              only:
                - master
            tags:
              only:
                - /^\d+\.\d+\.\d+$/ #for tag 1.2.3
      - publish-to-maven:
          requires:
            - publish-github-release
          filters:
            branches:
              only:
                - master
            tags:
              only:
                - /^\d+\.\d+\.\d+$/ #for tag 1.2.3