version: 2.1

orbs:
  changelog: onimur/github-changelog-generator@2.1.2
  mem: circleci/rememborb@0.0.1
  orb-tools: circleci/orb-tools@9.1.0

jobs:
  # Prepare build
  prepare:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      # Export Env_var
      - mem/remember:
          env_var: DATE_FORMAT
          value: "%d-%m-%y"
      - mem/remember:
          env_var: OUTPUT_CHANGELOG
          value: CHANGELOG.md
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Build apk
          command: ./gradlew assembleRelease
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports
      - run:
          name: Copy apk
          command: |
            mkdir -p artifacts
            cp -r app/build/outputs/apk/release/*.apk artifacts/${CIRCLE_PROJECT_REPONAME}-release.apk
      - store_artifacts:
          path: artifacts
          destination: artifacts
      - persist_to_workspace:
          root: ./
          paths:
            - artifacts
  # Publish on github releases
  publish-github-release:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: application
      # Get Env_Var
      - mem/recall:
          env_var: DATE_FORMAT
      - mem/recall:
          env_var: OUTPUT_CHANGELOG
      - run:
          name: List Files
          command: |
            apk add tree
            pwd
            tree application
            find .
      - run:
          name: Publish Release on GitHub
          command: |
            DATE=$(date +${DATE_FORMAT})
            TAG_WITHOUT_DOT="${CIRCLE_TAG//./}"
            TITLE="Handle Path Oz"
            URL_CHANGELOG="https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/blob/master/${OUTPUT_CHANGELOG}#${TAG_WITHOUT_DOT}-${DATE}"
            printf -v BODY "$(curl -s 'https://raw.githubusercontent.com/onimur/handle-path-oz/master/docs/RELEASE_TEMPLATE.md')" \
            "${TITLE}" "${DATE}" "${CIRCLE_TAG}" "${CIRCLE_BUILD_NUM}" "${CIRCLE_BUILD_URL}" "${OUTPUT_CHANGELOG}" "${URL_CHANGELOG}"
            ghr \
            -t ${GITHUB_TOKEN} \
            -u ${CIRCLE_PROJECT_USERNAME} \
            -r ${CIRCLE_PROJECT_REPONAME}  \
            -b "${BODY}" \
            -c ${CIRCLE_SHA1}  \
            -delete ${CIRCLE_TAG} application/artifacts
  #Upload to bintray(Jcenter), nexus(Maven Central) and GithubPackages
  publish-to-library:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Publish to Jcenter and Maven Central
          command: ./gradlew build bintrayUpload -PdryRun=false
      - run:
          name: Publish to Github Package
          command: ./gradlew publish
# Filters
orb_tagged_filters: &orb_tagged_filters
  branches:
    ignore: /.*/
  tags:
    only: /^\d+\.\d+\.\d+$/ #for tag 1.2.3

workflows:
  build: #runs job for all branches.
    jobs:
      - orb-tools/lint
      - orb-tools/shellcheck:
          exclude: "SC2002,SC1073,SC1009"
          requires: [orb-tools/lint]
      - prepare:
          requires: [orb-tools/shellcheck]
  tagged-publish: # run job for all tags
    jobs:
      - orb-tools/lint
      - orb-tools/shellcheck:
          # exclude: "SC2002,SC1073,SC1009"
          requires: [orb-tools/lint]
      - prepare:
          filters: *orb_tagged_filters
          requires: [orb-tools/shellcheck]
      - publish-github-release:
          requires: [prepare]
          filters: *orb_tagged_filters
      - publish-to-library:
          requires: [publish-github-release]
          filters: *orb_tagged_filters
      - changelog/changelog-custom:
          context: main-context
          steps:
            - mem/recall:
                env_var: DATE_FORMAT
            - mem/recall:
                env_var: OUTPUT_CHANGELOG
          push-git: true
          date-format: ${DATE_FORMAT}
          output: ${OUTPUT_CHANGELOG}
          requires: [prepare]
          filters: *orb_tagged_filters
