version: 2.1

orbs:
  changelog: onimur/github-changelog-generator@2.0.7

jobs:
  prepare:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Build apk
          command: ./gradlew assembleRelease
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports
      - run:
          name: Copy apk
          command: |
            mkdir -p artifacts
            cp -r app/build/outputs/apk/release/*.apk artifacts/${CIRCLE_PROJECT_REPONAME}-release.apk
      - store_artifacts:
          path: artifacts
          destination: artifacts
      - persist_to_workspace:
          root: ./
          paths:
            - artifacts

  #publish on github releases
  publish-github-release:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: application
      - run:
          name: List Files
          command: |
            apk add tree
            pwd
            tree application
      - run:
          name: Publish Release on GitHub
          command: |
            DATE=$(date +'%m-%d-%y')
            printf -v BODY "$(curl -s 'https://raw.githubusercontent.com/onimur/handle-path-oz/master/docs/RELEASE_TEMPLATE.md')" "${CIRCLE_PROJECT_REPONAME}" "${DATE}" "${CIRCLE_TAG}" "${CIRCLE_BUILD_NUM}" "${CIRCLE_BUILD_URL}"
            ghr \
            -t ${GITHUB_TOKEN} \
            -u ${CIRCLE_PROJECT_USERNAME} \
            -r ${CIRCLE_PROJECT_REPONAME}  \
            -b "${BODY}" \
            -c ${CIRCLE_SHA1}  \
            -delete ${CIRCLE_TAG} application/artifacts

  #Upload to bintray(Jcenter), nexus(Maven Central) and GithubPackages
  publish-to-library:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Publish to Jcenter and Maven Central
          command: ./gradlew build bintrayUpload -PdryRun=false
      - run:
          name: Publish to Github Package
          command: ./gradlew publish

orb_tagged_filters: &orb_tagged_filters
  branches:
    ignore: /.*/
  tags:
    only: /^\d+\.\d+\.\d+$/ #for tag 1.2.3

workflows:
  build: #runs job for all branches.
    jobs:
      - prepare
  tagged-publish: # run job for all tags
    jobs:
      - prepare:
          filters:  # required since `deploy` has tag filters AND requires `build`
            branches:
              ignore: /.*/ #ignore all branch
            tags:
              only: /.*/ # for all tags
      - publish-github-release:
          requires: [prepare]
          filters: *orb_tagged_filters
      - publish-to-library:
          requires: [publish-github-release]
          filters: *orb_tagged_filters
      - changelog/changelog-default:
          context: main-context
          push-git: true
          requires: [prepare]
          filters: *orb_tagged_filters
